# Generated by Django 3.1.5 on 2021-01-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, max_length=654),
        ),
    ]
