# Generated by Django 3.1.6 on 2021-02-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('id',)},
        ),
    ]
