# Generated by Django 3.1.6 on 2021-02-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_board', '0002_auto_20210204_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
    ]
