# Generated by Django 3.1.5 on 2021-01-31 03:13

import api_board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_board', '0002_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='user', max_length=20, validators=[api_board.models.validate_role]),
        ),
    ]
