# Generated by Django 3.1.6 on 2021-02-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_board', '0007_auto_20210205_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
    ]
