# Generated by Django 3.1.6 on 2021-02-05 10:37

import api_board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_board', '0008_auto_20210205_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', help_text="Administrator, moderator or user. By default 'user'", max_length=10, validators=[api_board.models.validate_role]),
        ),
    ]
