# Generated by Django 3.1.6 on 2021-02-05 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_board', '0010_auto_20210205_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
    ]
