# Generated by Django 3.1.6 on 2021-02-08 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_board', '0012_auto_20210205_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('id',)},
        ),
    ]
