# Generated by Django 3.1.6 on 2021-02-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_board', '0013_auto_20210208_0802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',), 'verbose_name_plural': 'categories'},
        ),
    ]
