# Generated by Django 3.1.6 on 2021-02-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_board', '0014_auto_20210209_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('User', 'user'), ('Moderator', 'moderator'), ('Admin', 'admin')], help_text="Administrator, moderator or user. By default 'user'", max_length=10),
        ),
    ]
